use_frameworks!

platform :ios, '10.0'

target 'KKPodTest_Example' do
  pod 'KKPodTest', :path => '../'

  target 'KKPodTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
